# -*- coding: utf-8 -*-
"""Holamundo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzZVIwo0CsmH_dDaADdDlyoqYZ3apdYQ
"""

print("Hola mundo")