# -*- coding: utf-8 -*-
"""import pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzZVIwo0CsmH_dDaADdDlyoqYZ3apdYQ
"""

import pandas as pd

file_path = "/spotify.csv"
df = pd.read_csv(file_path)

print(f"Info del DataFrame")
df.info()

print("Valores nulos por columna:")
valores_nulos = df.isnull().sum()
print(valores_nulos)

print("\nDescripción estadística de las variables numéricas:")
print(df.describe())

print("\nValores máximos y mínimos por variable numérica:")
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    print(f"{col}: min = {df[col].min()}, max = {df[col].max()}")

print("\nMedidas de tendencia central y dispersión:")
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    media = df[col].mean()
    mediana = df[col].median()
    desviacion = df[col].std()
    print(f"{col}: media = {media:.2f}, mediana = {mediana:.2f}, desviación estándar = {desviacion:.2f}")

print("\nConclusiones:")
print("- Si la media y la mediana son parecidas, la distribución es simétrica.")
print("- Si la media es mayor que la mediana, hay sesgo hacia la derecha (valores altos).")
print("- Si la desviación estándar es alta, hay mucha variabilidad en los datos.")
#mediana = df['release_year'].median()

def saludar(nombre):
  print(f"Hola, {nombre} :)")

saludar ("Fedrika")